# Generated by Django 5.1 on 2024-09-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dessins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_personnage', models.CharField(max_length=30)),
                ('date_realisation', models.DateField()),
                ('temps_passe', models.CharField(max_length=20)),
                ('materiel_utilise', models.CharField(max_length=255)),
                ('difficulte', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='dessins/')),
            ],
        ),
    ]
