# Generated by Django 5.1 on 2024-09-11 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dessin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_personnage', models.CharField(max_length=30)),
                ('date_realisation', models.DateField()),
                ('temps_passe', models.CharField(max_length=20)),
                ('materiel_utilise', models.CharField(max_length=255)),
                ('difficulte', models.CharField(max_length=255)),
                ('description', models.CharField(default='Pas de description', max_length=250)),
                ('image', models.ImageField(upload_to='dessins/')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('dessin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dessins.dessin')),
            ],
        ),
    ]
