# Generated by Django 5.1 on 2024-09-02 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dessins', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dessins',
            new_name='Dessin',
        ),
    ]
