# Generated by Django 5.1 on 2024-09-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dessins', '0002_rename_dessins_dessin'),
    ]

    operations = [
        migrations.AddField(
            model_name='dessin',
            name='description',
            field=models.CharField(default='Pas de description', max_length=250),
        ),
    ]
